=== lucasiragusa/docx_generator/schemas/flight_data_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "Flight_number": {
        "type": "string"
      },
      "Service_Type": {
        "type": "string"
      },
      "Eff": {
        "type": "string",
        "format": "date"
      },
      "Dis": {
        "type": "string",
        "format": "date"
      },
      "Days_of_operation": {
        "type": "string"
      },
      "Dept_Stn": {
        "type": "string"
      },
      "Dept_time_pax": {
        "type": "string"
      },
      "Arvl_Stn": {
        "type": "string"
      },
      "Arvl_time_pax": {
        "type": "string"
      },
      "Equipment": {
        "type": "string"
      },
      "Aircraft_configuration": {
        "type": "string"
      },
      "Departure_country": {
        "type": "string"
      },
      "Arrival_country": {
        "type": "string"
      }
    },
    "required": [
      "Flight_number",
      "Service_Type",
      "Eff",
      "Dis",
      "Days_of_operation",
      "Dept_Stn",
      "Dept_time_pax",
      "Arvl_Stn",
      "Arvl_time_pax",
      "Equipment",
      "Aircraft_configuration",
      "Departure_country",
      "Arrival_country"
    ]
  }

=== lucasiragusa/docx_generator/schemas/sample_schema.json
{
    "Flight_number": "EY123",
    "Service_Type": "J",
    "Eff": "01MAY22",
    "Dis": "31MAY22",
    "Days_of_operation": "1234567",
    "Dept_Stn": "AUH",
    "Dept_time_pax": "1000",
    "Arvl_Stn": "JFK",
    "Arvl_time_pax": "1600",
    "Equipment": "789",
    "Aircraft_configuration": "C12Y270",
    "Departure_country": "AE",
    "Arrival_country": "US"
  }
